import React, { useState, useEffect } from 'react';
import { Box, Typography, TextField, Button, Paper, Stack, Alert, CircularProgress } from '@mui/material';
import { useNavigate, Link, useSearchParams } from 'react-router-dom';
import client from '../api/client.js';
import { useAppStore } from '../store/useAppStore.js';
import { BsPersonPlus } from 'react-icons/bs';

export default function RegisterUser() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [adminCode, setAdminCode] = useState('');
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);
  const [isClientInvite, setIsClientInvite] = useState(false);
  const [emailDisabled, setEmailDisabled] = useState(false);
  
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const registerUser = useAppStore((s) => s.registerUser);

  useEffect(() => {
    const code = searchParams.get('code') || '';
    if (code) {
      setAdminCode(code);
      if (code.startsWith('CL-INV-')) {
        setIsClientInvite(true);
        // Fetch invite details to auto-fill email
        client.get(`/api/auth/invite-info/${code}`)
          .then((res) => {
            if (res.email) {
              setEmail(res.email);
              setEmailDisabled(true);
            }
          })
          .catch((err) => {
            console.error('Failed to load invite info:', err);
            setError(err.message || 'Invalid or expired invite link.');
          });
      }
    }
  }, [searchParams]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {
      await registerUser(name, email, password, adminCode);
      navigate('/');
    } catch (err) {
      setError(err.message || 'Registration failed');
    } finally {
      setLoading(false);
    }
  };

  if (!isClientInvite) {
    return (
      <Box sx={{ maxWidth: 500, mx: 'auto', mt: { xs: 4, md: 8 } }}>
        <Paper elevation={0} sx={{ p: 4, borderRadius: 3, border: '1px solid', borderColor: 'divider', textAlign: 'center' }}>
          <Stack spacing={3} alignItems="center">
            <Typography variant="h5" color="error.main" fontWeight={700}>
              Sign Up Restricted
            </Typography>
            <Typography color="text.secondary">
              Direct registration is disabled. Training institutes need a valid client registration link generated by the Super Admin to register.
            </Typography>
            <Typography variant="body2" color="text.secondary">
              Students do not need to register. You can log in directly using your email and the invite token provided by your institute.
            </Typography>
            <Button variant="contained" onClick={() => navigate('/login')} sx={{ px: 4 }}>
              Go to Login
            </Button>
          </Stack>
        </Paper>
      </Box>
    );
  }

  return (
    <Box sx={{ maxWidth: 400, mx: 'auto', mt: { xs: 4, md: 8 } }}>
      <Paper elevation={0} sx={{ p: 4, borderRadius: 3, border: '1px solid', borderColor: 'divider' }}>
        <Stack spacing={3}>
          <Box sx={{ textAlign: 'center' }}>
            <Typography variant="h4" color="primary.main" gutterBottom>
              {isClientInvite ? 'Register Training Institute' : 'Create Account'}
            </Typography>
            <Typography color="text.secondary">
              {isClientInvite ? 'Set up your institute and start training students' : 'Join the GST Simulator to save your progress'}
            </Typography>
          </Box>

          {error && <Alert severity="error">{error}</Alert>}

          <form onSubmit={handleSubmit}>
            <Stack spacing={2.5}>
              <TextField
                label={isClientInvite ? 'Institute Name' : 'Full Name'}
                placeholder={isClientInvite ? 'e.g. Aadhira Academy' : ''}
                fullWidth
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
              <TextField
                label="Email Address"
                type="email"
                fullWidth
                required
                disabled={emailDisabled}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
              <TextField
                label="Password"
                type="password"
                fullWidth
                required
                inputProps={{ minLength: 6 }}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
              <TextField
                label={isClientInvite ? 'Client Invite Code' : 'Teacher Invite Code (Optional)'}
                fullWidth
                disabled={isClientInvite}
                placeholder={isClientInvite ? '' : 'Leave blank if you are a student'}
                value={adminCode}
                onChange={(e) => setAdminCode(e.target.value)}
              />
              <Button
                type="submit"
                variant="contained"
                size="large"
                disabled={loading || !email || !password || !name}
                startIcon={loading ? <CircularProgress size={18} color="inherit" /> : <BsPersonPlus size={18} />}
                sx={{ mt: 2, py: 1.5, fontSize: '1rem', borderRadius: 2 }}
              >
                {loading ? 'Registering...' : (isClientInvite ? 'Register Institute' : 'Sign Up')}
              </Button>
            </Stack>
          </form>

          <Typography align="center" variant="body2" color="text.secondary">
            Already have an account?{' '}
            <Link to="/login" style={{ color: '#1a3c6e', fontWeight: 600, textDecoration: 'none' }}>
              Log in
            </Link>
          </Typography>
        </Stack>
      </Paper>
    </Box>
  );
}
